# IO
input_path: "../../../../datasets/terra_02_000004.asc"
output_dir: "outputs"

# Task parameters
constant_value: 10.0
multiply_factor: 2.0
add_value: 5.0

gaussian_sigma: 2.0
moving_average_window: 5

colormap: "viridis"

filter_min: 0.5
filter_max: 0.9

use_scalar_axis: 2  # Z as scalar by default